[package]
name = "adventofcode2022"
version = "0.0.0"
edition = "2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = [ "cookies", "blocking" ] }

[lib]
name = "common"
path = "common.rs"
